project_name: jcconv
before:
  hooks:
  - go get github.com/inconshreveable/mousetrap github.com/spf13/cobra github.com/spf13/viper github.com/go-ego/cedar github.com/mitchellh/go-homedir
  - go generate ./...
  - mkdir -p /go/src/github.com/jackytck/
  - ln -s /github/workspace /go/src/github.com/jackytck/go-chinese-converter
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
